# Generated by Django 5.0.1 on 2026-03-17 12:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('type', models.CharField(choices=[('accident', 'Accident'), ('theft', 'Theft'), ('fire', 'Fire'), ('medical', 'Medical'), ('death', 'Death'), ('disability', 'Disability'), ('property_damage', 'Property Damage'), ('third_party', 'Third Party'), ('other', 'Other')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('incident_date', models.DateField()),
                ('incident_location', models.CharField(max_length=255)),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('documents_requested', 'Documents Requested'), ('assessment_complete', 'Assessment Complete'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('settled', 'Settled')], db_index=True, default='submitted', max_length=30)),
                ('assessor_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('filed_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_date', models.DateTimeField(blank=True, null=True)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'claims',
                'ordering': ['-filed_date'],
            },
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('police_report', 'Police Report'), ('medical_report', 'Medical Report'), ('photos', 'Photos'), ('videos', 'Videos'), ('receipts', 'Receipts'), ('invoices', 'Invoices'), ('witness_statement', 'Witness Statement'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('file_url', models.URLField()),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'claim_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('cheque', 'Cheque')], max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('mpesa_phone', models.CharField(blank=True, max_length=20)),
                ('cheque_number', models.CharField(blank=True, max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'claim_settlements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Claim Status Histories',
                'db_table': 'claim_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
