# Generated by Django 5.0.1 on 2026-03-17 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_claim_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimsettlement',
            name='claim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='claimsettlement',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimstatushistory',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='claims.claim'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['policy', 'status'], name='claims_policy__a9ba66_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['user', 'status'], name='claims_user_id_7db873_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['assessor', 'status'], name='claims_assesso_f14353_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', 'filed_date'], name='claims_status_ffa8aa_idx'),
        ),
    ]
