# Generated by Django 5.0.1 on 2026-03-17 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(choices=[('quote_generated', 'Quote Generated'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('underwriting', 'Underwriting'), ('document_verification', 'Document Verification'), ('approval', 'Approval'), ('policy_issuance', 'Policy Issuance'), ('certificate_generation', 'Certificate Generation'), ('active', 'Active')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflow_stages', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stages', to='policies.policy')),
            ],
            options={
                'db_table': 'workflow_stages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['policy', 'status'], name='workflow_st_policy__91c450_idx'), models.Index(fields=['assigned_to', 'status'], name='workflow_st_assigne_aa7ea1_idx')],
            },
        ),
    ]
