# Generated by Django 5.0.1 on 2026-03-17 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyreview',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='policyreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policytype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_types', to='policies.policycategory'),
        ),
        migrations.AddField(
            model_name='policytype',
            name='insurance_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_types', to='policies.insurancecompany'),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='policies.policytype'),
        ),
        migrations.AlterUniqueTogether(
            name='policyreview',
            unique_together={('policy', 'user')},
        ),
        migrations.AddIndex(
            model_name='policytype',
            index=models.Index(fields=['category', 'is_active'], name='policy_type_categor_910153_idx'),
        ),
        migrations.AddIndex(
            model_name='policytype',
            index=models.Index(fields=['insurance_company', 'is_active'], name='policy_type_insuran_a2e9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='policytype',
            index=models.Index(fields=['status'], name='policy_type_status_ccebf6_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['user', 'status'], name='policies_user_id_3c83de_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['status', 'end_date'], name='policies_status_8ccd41_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_number'], name='policies_policy__ca1bbf_idx'),
        ),
    ]
