# Generated by Django 5.0.1 on 2026-05-01 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(help_text='Year of manufacture')),
                ('registration_number', models.CharField(max_length=20)),
                ('chassis_number', models.CharField(blank=True, max_length=50)),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('pickup', 'Pick-up / Double Cab'), ('van', 'Van / Minivan'), ('bus', 'Bus / Minibus'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('other', 'Other')], default='sedan', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('value', models.DecimalField(decimal_places=2, help_text='Current market value in KES', max_digits=15)),
                ('logbook_url', models.URLField(blank=True, help_text='S3 URL of uploaded logbook', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
