# Generated by Django 5.0.1 on 2026-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_add_vehicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='policytype',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Rate percentage for commission-based pricing, e.g. 5.0000 means 5%', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='policytype',
            name='rate_type',
            field=models.CharField(choices=[('flat', 'Flat Premium'), ('commission_percent', 'Commission % of Insured Value')], default='flat', help_text='flat: use base_premium directly; commission_percent: rate = commission_rate % of vehicle/asset value', max_length=20),
        ),
    ]
