# Generated by Django 5.0.1 on 2026-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_add_rate_fields_to_policy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='cover_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry of the 1-month comprehensive cover given after initial payment', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='initial_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='40% of estimated premium — due at purchase for comprehensive', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='payment_stage',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('initial_pending', 'Initial Payment Pending'), ('valuation_pending', 'Vehicle Valuation Pending'), ('valuation_complete', 'Valuation Complete'), ('installment_1_pending', 'Installment 1 Pending'), ('installment_2_pending', 'Installment 2 Pending'), ('fully_paid', 'Fully Paid')], db_index=True, default='not_applicable', max_length=30),
        ),
        migrations.AddField(
            model_name='policy',
            name='true_premium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual premium after vehicle valuation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='valuation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='valuation_due_at',
            field=models.DateTimeField(blank=True, help_text='1 month from policy start', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='valuation_extension_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='valuation_extension_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='valuation_letter_url',
            field=models.URLField(blank=True, help_text='Valuation report uploaded by admin', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='valuation_required',
            field=models.BooleanField(default=False),
        ),
    ]
