# Generated by Django 5.0.1 on 2026-03-17 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('id_copy', 'ID Copy'), ('kra_pin', 'KRA PIN'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('logbook', 'Logbook'), ('certificate', 'Insurance Certificate'), ('receipt', 'Receipt'), ('policy_document', 'Policy Document'), ('claim_document', 'Claim Document'), ('medical_card', 'Medical Card'), ('other', 'Other')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=255)),
                ('s3_key', models.CharField(max_length=500, unique=True)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
