# Generated by Django 5.0.1 on 2026-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='schedule_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('initial', 'Initial Payment (40%)'), ('installment_1', 'Balance Installment 1 (30%)'), ('installment_2', 'Balance Installment 2 (30%)')], default='full', max_length=20),
        ),
    ]
